language: node_js

# Force Travis CI to run jobs in VMs instead of Docker containers.
# - https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
# - https://docs.travis-ci.com/user/reference/trusty/#fully-virtualized-via-sudo-required
sudo: required

dist: trusty
node_js:
  - '10.7.0'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - ./node_modules

install:
  - yarn

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint:ts
  - npm run test:unit

after_success:
  - codecov
