name: Test, Build and Deploy

# Run only on pushes and if branch is master
on:
  push:
    branches:
      - master

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10, 11]

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v1.1.0
        with:
          version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version
      - run: yarn --version
      
      - name: Install dependencies
        run: yarn
        
      - name: Build angular-mdc-web
        run: yarn run build:release

      - name: Run tests
        run: | 
          yarn lint
          yarn test

      - name: Run Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Build and Deploy Documentation
        if: matrix.node == 11
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: demos/dist/angular-mdc-demos/
          BUILD_SCRIPT: cd demos && npm install -g @angular/cli && npm install && ng build --prod && cd ..
